In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [2]:
def ensemble_acc(classes):
    m0  = pd.read_csv(f'../val_test_results/GT_double_{classes}C_0F_test.csv')
    m1  = pd.read_csv(f'../val_test_results/GT_double_{classes}C_1F_test.csv')
    m2  = pd.read_csv(f'../val_test_results/GT_double_{classes}C_2F_test.csv')
    m3  = pd.read_csv(f'../val_test_results/GT_double_{classes}C_3F_test.csv')
    m4  = pd.read_csv(f'../val_test_results/GT_double_{classes}C_3F_test.csv')
    m = pd.DataFrame()

    m['preds_0'] = m0['preds']
    m['preds_1'] = m1['preds']
    m['preds_2'] = m2['preds']
    m['preds_3'] = m3['preds']
    m['preds_4'] = m3['preds']
    
    m['majority'] = stats.mode(np.array(m.T))[0].T
    
    Acc_m0 = round(len(m0[m0['label']==m0['preds']])/len(m0), 3)
    Acc_m1 = round(len(m1[m1['label']==m1['preds']])/len(m1), 3)
    Acc_m2 = round(len(m2[m2['label']==m2['preds']])/len(m2), 3)
    Acc_m3 = round(len(m3[m3['label']==m3['preds']])/len(m3), 3)
    
    print('Acc m0:', round(len(m0[m0['label']==m0['preds']])/len(m0), 3))
    print('Acc m1:', round(len(m1[m1['label']==m1['preds']])/len(m1), 3))
    print('Acc m2:', round(len(m2[m2['label']==m2['preds']])/len(m2), 3))
    print('Acc m3:', round(len(m3[m3['label']==m3['preds']])/len(m3), 3))
    
    print()
    
    acces = np.array([Acc_m0, Acc_m1, Acc_m2, Acc_m3])*100
    
    print('Mean Acc:', round (np.mean(acces),3), np.std(acces))
    print('Acc ensemble:',round(len(m0[m0['label']==m['majority']])/len(m), 3))
    print()
    return m

In [6]:
ensemble_acc(5) # change 2, 3, or 5

Acc m0: 0.673
Acc m1: 0.705
Acc m2: 0.695
Acc m3: 0.673

Mean Acc: 68.65 1.3955285736952807
Acc ensemble: 0.693

     preds_0  preds_1  preds_2  preds_3  preds_4  majority
0          3        3        3        3        3         3
1          1        1        1        1        1         1
2          0        0        0        2        2         0
3          2        2        1        2        2         2
4          4        4        4        4        4         4
..       ...      ...      ...      ...      ...       ...
392        2        2        2        1        1         2
393        2        2        2        2        2         2
394        2        2        2        2        2         2
395        0        0        0        0        0         0
396        0        0        0        0        0         0

[397 rows x 6 columns]